import Navbar from './components/Navbar'
import ProtectedRoute from './components/ProtectedRoute'
import { UsuarioProvider } from './contexts/UsuarioContext'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UsuarioProvider>
          <ProtectedRoute>
            <Navbar />
            <main style={{ backgroundColor: '#F05B5B' }}>
              {children}
            </main>
          </ProtectedRoute>
        </UsuarioProvider>
      </body>
    </html>
  )
}
